# Generated by Django 5.2.3 on 2025-06-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Produto')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo do Produto')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade em Estoque')),
            ],
        ),
    ]
