# Generated by Django 5.2.3 on 2025-07-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='created_prod',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='produtos',
            name='update_prod',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
