# Generated by Django 5.2.3 on 2025-07-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_produtos_created_prod_produtos_update_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='tipo',
            field=models.IntegerField(verbose_name='Tipo do Produto'),
        ),
    ]
