# Generated by Django 5.2.3 on 2025-07-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_produtos_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do cliente')),
                ('nome_cliente', models.CharField(max_length=100, verbose_name='Nome do cliente')),
                ('tempo_estadia', models.IntegerField(verbose_name='Tempo de estadia')),
                ('created_prod', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_prod', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
