# Generated by Django 5.2.3 on 2025-07-21 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_clientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='created_prod',
            new_name='created_cad',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='update_prod',
            new_name='update_cad',
        ),
        migrations.AddField(
            model_name='clientes',
            name='contato',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='telefone celular'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='medida',
            field=models.CharField(default='UND', max_length=5, verbose_name='Unidade de Medida'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='vendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID da venda')),
                ('data_hora', models.DateTimeField(auto_now_add=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor total')),
                ('desconto', models.IntegerField(verbose_name='desconto')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='pagamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do pagamento')),
                ('forma_pag', models.IntegerField(verbose_name='Forma de pagamento')),
                ('valor_pag', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor pago')),
                ('troco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor pago')),
                ('id_vendas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.vendas')),
            ],
        ),
        migrations.CreateModel(
            name='itens_venda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do item vendas')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade vendido')),
                ('preco_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.produtos')),
                ('id_vendas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.vendas')),
            ],
        ),
    ]
