# Generated by Django 5.2.3 on 2025-07-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_produtos_preco_cesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
