# Generated by Django 5.2.3 on 2025-08-06 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_cesta_usuario_clientes_usuario_itens_venda_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='tempo_estadia',
        ),
    ]
